import UserProvider from "@/context/user";
import { FormProvider } from "@/context/seller";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import "./nprogress.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import type { Metadata } from "next";
import { Next13NProgress } from "nextjs13-progress";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-red-hat",
});

export const metadata: Metadata = {
  title: "Poultry Collective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={redHatDisplay.variable}>
        <FormProvider>
          <UserProvider>{children}</UserProvider>
        </FormProvider>
        <ToastContainer />
        <Next13NProgress
          color="#0d5c3d"
          startPosition={0.3}
          stopDelayMs={50}
          height={3}
          showOnShallow={true}
        />
      </body>
    </html>
  );
}
