import type { Metadata } from "next";
import { Red_Hat_Display } from "next/font/google";
import "./globals.css";
import UserProvider from "@/context/user";
import { FormProvider } from "@/context/seller";

const redHatDisplay = Red_Hat_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-red-hat",
});

export const metadata: Metadata = {
  title: "Poultry Collective",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <FormProvider>
          <body className={redHatDisplay.variable}>{children}</body>
        </FormProvider>
      </UserProvider>
    </html>
  );
}
